name: aurora_push_service
description: A new Flutter plugin project for Aurora OS to get Push Messages.
version: 0.2.0
publish_to: https://pub-aurora.friflex.com
homepage: "https://github.com/smmarty/aurora_flutter/tree/main/packages/aurora_push_service"

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_async: ^1.3.1

flutter:
  plugin:
    platforms:
      aurora:
        pluginClass: AuroraPushPlugin